version: "3.7"

services:
  https:
    image: httpd:latest
    ports:
      - "5657:80"
      
  edgedb:
   image: edgedb/edgedb:latest
   command:
     - --admin-ui=enabled
   environment:
     EDGEDB_SERVER_SECURITY: "insecure_dev_mode"
     EDGEDB_SERVER_PASSWORD: "portainer"
   ports:
      - "5656:5656"
   volumes:
    - "./dbschema:/dbschema"
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:5656/server/status/ready"]
     interval: 5s
     timeout: 1s
     retries: 10
